name: "WFSL Admission Guard"
description: "Deterministic, deny-by-default admission enforcement with audit-grade evidence."
author: "Wynergy Fibre Solutions Ltd"

branding:
  icon: "shield"
  color: "blue"

inputs:
  mode:
    description: "Admission mode (repo | marketplace)"
    required: false
    default: "repo"

runs:
  using: "node20"
  main: "dist-action/index.cjs"
